baseURL: ""
languageCode: en-us
title: The Elemental Epistles Talk Writing Guide

theme: "PaperMod"
# Support at https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/


params:
    profileMode:
        enabled: true
        title: "Talk Writing Guide" # optional default will be site title
        subtitle: "A religious sermon writing guide for the rest of us"
        buttons:
        - name: "Get Started"
          url: "/start/"

    # ShowBreadCrumbs: true
    ShowShareButtons: true
    # ShowReadingTime: true
    DateFormat: "2 January 2006"
    assets:
        disableHLJS: true
    # cover:
    #     linkFullImages: true
    env: production
    disableScrollToTop: false
    ShowCodeCopyButtons: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: true
    math: true
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        # guessSyntax: true
        # lineNos: true
        # noClasses: false
        style: dracula
        # style: native # see https://xyproto.github.io/splash/docs/all.html

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
  - identifier: start
    name: Start
    url: /start/
    weight: 2
  # - identifier: search
  #   name: Search
  #   url: /search/
  #   weight: 4


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary