baseURL: ""
languageCode: en-us
title: Design Your You

theme: "PaperMod"
# Support at https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/


params:
    homeInfoParams:
        title: "Welcome to Design Your You"
        content: "This website is a compilation of interesting projects and random mutterings by Landon Taylor."

    socialIcons: 
        - name: "github"
          url: "https://github.com/landonjefftaylor"
        - name: "website"
          url: "<link2>"

    # ShowBreadCrumbs: true
    ShowShareButtons: true
    ShowReadingTime: true
    DateFormat: "2 January 2006"
    assets:
        disableHLJS: true
    # cover:
    #     linkFullImages: true
    env: production
    disableScrollToTop: false
    ShowCodeCopyButtons: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: true
    math: true
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        # guessSyntax: true
        # lineNos: true
        # noClasses: false
        style: dracula
        # style: native # see https://xyproto.github.io/splash/docs/all.html

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 2
  - identifier: docs
    name: Docs
    url: /documentation/
    weight: 3
  - identifier: search
    name: Search
    url: /search/
    weight: 4




outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary